"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.14.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from datetime import timedelta
import os
import sys
import environ
from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
# settings.py lives at backend/config/settings.py, so two hops reach backend/.
# (Was three hops when this was config/settings/base.py; the flatten left it
# pointing at the repo root, which read the wrong .env and MEDIA_ROOT.)
BASE_DIR = Path(__file__).resolve().parent.parent

env = environ.Env(
    DEBUG=(bool, False)
)
environ.Env.read_env(BASE_DIR / '.env')

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('DJANGO_SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env("DEBUG")

# Comma-separated hostnames this deploy serves (env-driven). Empty is fine in
# dev because DEBUG=True bypasses the host check; REQUIRED once DEBUG is False,
# or Django rejects every request with DisallowedHost. On Railway set e.g.
# ALLOWED_HOSTS=hephzibah-api.up.railway.app,api.hephluxe.com
ALLOWED_HOSTS = env.list('ALLOWED_HOSTS', default=[])

# Origins trusted for unsafe (POST) requests behind HTTPS — the Django admin
# login needs this once served on a real domain with DEBUG=False. Django 4+
# requires the scheme (https://…). Defaults to each ALLOWED_HOST as https:// so
# the common case needs no extra config; override via CSRF_TRUSTED_ORIGINS to
# add others (e.g. a www host).
CSRF_TRUSTED_ORIGINS = env.list(
    'CSRF_TRUSTED_ORIGINS',
    default=[f'https://{host}' for host in ALLOWED_HOSTS if host],
)


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    'corsheaders',
    'rest_framework',
    'rest_framework_simplejwt.token_blacklist',
    'storages',
    'django_celery_beat',

    'apps.accounts',
    'apps.core',
    'apps.contacts',
    'apps.conversations',
    'apps.events',
    'apps.meetings',
    'apps.portal',
    'apps.reminders',
    'apps.inquiries',
    'apps.documents',
    'apps.budgets',
    'apps.document_hub',
    'apps.notifications',
]

REST_FRAMEWORK = {
        'DEFAULT_AUTHENTICATION_CLASSES': (
            'rest_framework_simplejwt.authentication.JWTAuthentication',
        ),
    # Unhandled exceptions get the standard {detail, code} envelope + logging.
    # DRF-handled 4xx responses pass through unchanged (see apps/core/exceptions.py).
    'EXCEPTION_HANDLER': 'apps.core.exceptions.custom_exception_handler',
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '50/day',    # Unauthenticated (login attempts, etc.)
        'user': '500/day',   # Authenticated users
    },
}

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    # Serves collected static files (Django admin CSS/JS) straight from the app
    # in production — no separate static host/CDN needed. Placed directly after
    # SecurityMiddleware per WhiteNoise's docs. A no-op under `runserver` in dev,
    # which serves static via staticfiles finders instead.
    'whitenoise.middleware.WhiteNoiseMiddleware',
    # Correlation ID for every request, propagated into logs + Celery tasks.
    'apps.core.middleware.RequestIDMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'config.middleware.ForcePasswordChangeMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # Catches django-ratelimit's Ratelimited exception and renders RATELIMIT_VIEW
    # (the standard 429 body). Must come last so it wraps the whole chain.
    'django_ratelimit.middleware.RatelimitMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': env.db('DATABASE_URL')
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
# collectstatic gathers every app's static files here, and WhiteNoise serves
# them from here in production. Required for `manage.py collectstatic` to run at
# all. Gitignored (see .gitignore: staticfiles/).
STATIC_ROOT = BASE_DIR / 'staticfiles'
# Media lives on Cloudflare R2 in all real use (see the STORAGES block below) —
# there is no local-disk media. MEDIA_URL is only the base path the in-memory
# storage (used when R2 is off, i.e. tests/CI) builds relative URLs from; there
# is deliberately no MEDIA_ROOT and no filesystem media directory.
MEDIA_URL = '/media/'


# ── Production hardening (only when DEBUG is off) ──
# Railway/Render terminate TLS at their edge and forward the request over plain
# HTTP with X-Forwarded-Proto; Django must trust that header to know the origin
# request was HTTPS — otherwise secure-cookie and HTTPS detection break behind
# the proxy. Kept out of dev so local http://localhost keeps working.
if not DEBUG:
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    # Opt-in: a hard HTTP->HTTPS redirect can interfere with a platform's
    # plain-HTTP healthcheck, so it's off unless you set SECURE_SSL_REDIRECT=True.
    SECURE_SSL_REDIRECT = env.bool('SECURE_SSL_REDIRECT', default=False)

    # HSTS — instruct browsers to only ever reach this domain over HTTPS. Unlike
    # SECURE_SSL_REDIRECT this is a response header, so it can't fight a plain-HTTP
    # healthcheck; it's safe behind Railway's always-HTTPS edge. Env-tunable so a
    # first deploy can start conservative and ramp up once HTTPS is confirmed end
    # to end — set SECURE_HSTS_SECONDS=31536000 (1 year) before submitting to the
    # browser preload list; 0 disables. A positive value also clears Django's
    # `check --deploy` security.W004/W005/W021 warnings.
    SECURE_HSTS_SECONDS = env.int('SECURE_HSTS_SECONDS', default=3600)
    SECURE_HSTS_INCLUDE_SUBDOMAINS = env.bool('SECURE_HSTS_INCLUDE_SUBDOMAINS', default=True)
    SECURE_HSTS_PRELOAD = env.bool('SECURE_HSTS_PRELOAD', default=True)


# ── Media storage: Cloudflare R2 (S3-compatible) for all real use ──
# https://docs.djangoproject.com/en/5.2/ref/settings/#storages
#
# This platform stores media on R2 only — there is NO local-disk storage path.
# Set USE_R2_STORAGE=True with the R2 credentials in every real environment
# (dev, staging, production). When it's off, media falls back to Django's
# in-memory storage (RAM, non-persistent) — used purely so tests/CI can run
# without R2 credentials or network; nothing is ever written to the filesystem.
USE_R2_STORAGE = env.bool('USE_R2_STORAGE', default=False)

if USE_R2_STORAGE:
    STORAGES = {
        "default": {
            "BACKEND": "storages.backends.s3.S3Storage",
        },
        "staticfiles": {
            # Compress + hash static files, and serve them via WhiteNoise. Only
            # active after `collectstatic` (which the deploy runs); `runserver`
            # in dev bypasses it, so local admin still works without collecting.
            "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
        },
    }
    AWS_ACCESS_KEY_ID = env('R2_ACCESS_KEY_ID')
    AWS_SECRET_ACCESS_KEY = env('R2_SECRET_ACCESS_KEY')
    AWS_STORAGE_BUCKET_NAME = env('R2_BUCKET_NAME', default='hepz')
    AWS_S3_ENDPOINT_URL = env('R2_ENDPOINT_URL')
    AWS_S3_REGION_NAME = 'auto'  # R2 has no regions; boto3 still requires a value
    AWS_S3_ADDRESSING_STYLE = 'path'  # R2 doesn't support AWS-style virtual-hosted-bucket subdomains
    AWS_S3_SIGNATURE_VERSION = 's3v4'
    AWS_DEFAULT_ACL = None  # R2 doesn't support per-object ACLs the way S3 does
    AWS_S3_FILE_OVERWRITE = False  # never silently clobber a same-named upload
    # Signed, expiring URLs — client documents/receipts/contracts shouldn't be
    # reachable by anyone who guesses or shares the URL.
    AWS_QUERYSTRING_AUTH = True
    AWS_QUERYSTRING_EXPIRE = env.int('R2_SIGNED_URL_EXPIRE_SECONDS', default=3600)

    # ── Public display images (event covers, day images, contact photos) ──
    # These are shown inline by the frontend and cached in already-fetched event
    # JSON, so a 1h signed URL would become a broken image an hour later. Point
    # them at a SEPARATE public R2 bucket (with a custom domain / r2.dev URL) so
    # they're served with unsigned, long-lived URLs — see apps/core/storages.py.
    # Leave both blank to keep images on the default signed storage above (safe:
    # images still work, just with the 1h signature). Documents ALWAYS stay on
    # the default signed storage regardless.
    R2_PUBLIC_BUCKET_NAME = env('R2_PUBLIC_BUCKET_NAME', default='')
    R2_PUBLIC_URL = env('R2_PUBLIC_URL', default='')
else:
    STORAGES = {
        "default": {
            # In-memory (RAM), not local disk — non-persistent, for tests/CI only.
            # Every real environment sets USE_R2_STORAGE=True and uses R2 above.
            "BACKEND": "django.core.files.storage.InMemoryStorage",
        },
        "staticfiles": {
            # Compress + hash static files, and serve them via WhiteNoise. Only
            # active after `collectstatic` (which the deploy runs); `runserver`
            # in dev bypasses it, so local admin still works without collecting.
            "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
        },
    }


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(days=1),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
    "UPDATE_LAST_LOGIN": False,

    "ALGORITHM": "HS256",
    "VERIFYING_KEY": "",
    "AUDIENCE": None,
    "ISSUER": None,
    "JSON_ENCODER": None,
    "JWK_URL": None,
    "LEEWAY": 0,

    "AUTH_HEADER_TYPES": ("Bearer",),
    "AUTH_HEADER_NAME": "HTTP_AUTHORIZATION",
    "USER_ID_FIELD": "id",
    "USER_ID_CLAIM": "user_id",
    "USER_AUTHENTICATION_RULE": "rest_framework_simplejwt.authentication.default_user_authentication_rule",
    "ON_LOGIN_SUCCESS": "rest_framework_simplejwt.serializers.default_on_login_success",
    "ON_LOGIN_FAILED": "rest_framework_simplejwt.serializers.default_on_login_failed",

    "AUTH_TOKEN_CLASSES": ("rest_framework_simplejwt.tokens.AccessToken",),
    "TOKEN_TYPE_CLAIM": "token_type",
    "TOKEN_USER_CLASS": "rest_framework_simplejwt.models.TokenUser",

    "JTI_CLAIM": "jti",

    "SLIDING_TOKEN_REFRESH_EXP_CLAIM": "refresh_exp",
    "SLIDING_TOKEN_LIFETIME": timedelta(minutes=5),
    "SLIDING_TOKEN_REFRESH_LIFETIME": timedelta(days=1),

    "TOKEN_OBTAIN_SERIALIZER": "rest_framework_simplejwt.serializers.TokenObtainPairSerializer",
    "TOKEN_REFRESH_SERIALIZER": "rest_framework_simplejwt.serializers.TokenRefreshSerializer",
    "TOKEN_VERIFY_SERIALIZER": "rest_framework_simplejwt.serializers.TokenVerifySerializer",
    "TOKEN_BLACKLIST_SERIALIZER": "rest_framework_simplejwt.serializers.TokenBlacklistSerializer",
    "SLIDING_TOKEN_OBTAIN_SERIALIZER": "rest_framework_simplejwt.serializers.TokenObtainSlidingSerializer",
    "SLIDING_TOKEN_REFRESH_SERIALIZER": "rest_framework_simplejwt.serializers.TokenRefreshSlidingSerializer",

    "CHECK_REVOKE_TOKEN": False,
    "REVOKE_TOKEN_CLAIM": "hash_password",
    "CHECK_USER_IS_ACTIVE": True,
}

AUTH_USER_MODEL = "accounts.User"

# NOTE: email used to send via Django's SMTP backend here
# (EMAIL_BACKEND/HOST/PORT/USE_TLS/HOST_USER/HOST_PASSWORD, plus
# DEFAULT_FROM_EMAIL). All outbound mail now goes through Brevo's
# transactional API instead — see apps/notifications/services.py — and every
# Brevo template carries its own sender identity, so DEFAULT_FROM_EMAIL is
# gone too.

# Required, deliberately: an unusable email pipeline should fail loudly at
# boot, not silently on the first send — same reasoning as FRONTEND_BASE_URL.
BREVO_API_KEY = env('BREVO_API_KEY')
if not BREVO_API_KEY.strip():
    raise ImproperlyConfigured(
        "BREVO_API_KEY must be set — every outbound email (reminders, "
        "payment/meeting digests, phase updates, credentials, password "
        "resets, ...) goes through Brevo's API. See apps/notifications/services.py."
    )

# One Brevo template ID per notifications.NotificationType — build the
# matching template in the Brevo dashboard first, then set its numeric ID
# here. See apps/notifications/README.md for the exact params each template
# should expect.
BREVO_TEMPLATE_NEW_REMINDER = env.int('BREVO_TEMPLATE_NEW_REMINDER')
BREVO_TEMPLATE_PAYMENT_DUE = env.int('BREVO_TEMPLATE_PAYMENT_DUE')
BREVO_TEMPLATE_MEETING_PREP_DUE = env.int('BREVO_TEMPLATE_MEETING_PREP_DUE')
BREVO_TEMPLATE_PHASE_ADVANCED = env.int('BREVO_TEMPLATE_PHASE_ADVANCED')
BREVO_TEMPLATE_EVENT_DETAILS_UPDATED = env.int('BREVO_TEMPLATE_EVENT_DETAILS_UPDATED')
BREVO_TEMPLATE_DOCUMENT_ADDED = env.int('BREVO_TEMPLATE_DOCUMENT_ADDED')
BREVO_TEMPLATE_INVOICE_ISSUED = env.int('BREVO_TEMPLATE_INVOICE_ISSUED')
BREVO_TEMPLATE_RECEIPT_ISSUED = env.int('BREVO_TEMPLATE_RECEIPT_ISSUED')
BREVO_TEMPLATE_MILESTONE_PAID = env.int('BREVO_TEMPLATE_MILESTONE_PAID')
BREVO_TEMPLATE_USER_CREDENTIALS = env.int('BREVO_TEMPLATE_USER_CREDENTIALS')
BREVO_TEMPLATE_PASSWORD_RESET = env.int('BREVO_TEMPLATE_PASSWORD_RESET')

# Single Redis source of truth. Celery's broker + result backend and the Django
# cache (rate-limit counters, /health/ready) all derive from REDIS_URL, so one
# URL wires everything — the home server hands out one Redis with a per-project
# DB index. The explicit CELERY_* / CACHE_REDIS_URL vars still override if you
# want them on a different instance or DB index.
REDIS_URL = env('REDIS_URL', default='')
CELERY_BROKER_URL = env('CELERY_BROKER_URL', default='') or REDIS_URL
CELERY_RESULT_BACKEND = env('CELERY_RESULT_BACKEND', default='') or REDIS_URL
if not CELERY_BROKER_URL:
    raise ImproperlyConfigured(
        "Set REDIS_URL (or CELERY_BROKER_URL) — Celery needs a Redis broker, "
        "e.g. redis://192.168.2.21:6379/4."
    )
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'UTC'

# ── Keep Redis chatter (and Railway Redis load) low ──
# Every task here is fire-and-forget (notifications, digests) — nothing calls
# .get()/AsyncResult or uses chords/groups — so storing a per-task result just
# burns Redis writes for data no one reads. And a Redis-broker worker's biggest
# source of *idle* command volume is its background broadcast traffic
# (gossip/mingle/heartbeat) plus the remote-control mailbox — none of which this
# single-worker deployment needs. Turning them off keeps Redis near-silent when
# there's no work, while normal task delivery (a blocking BRPOP) is unaffected.
# The matching worker flags (--without-gossip/mingle/heartbeat) are in the Procfile.
CELERY_TASK_IGNORE_RESULT = True
CELERY_WORKER_ENABLE_REMOTE_CONTROL = False
CELERY_WORKER_SEND_TASK_EVENTS = False
# Reconnect instead of crashing if a worker/beat boots a moment before Redis is
# reachable on Railway (also silences a Celery 6 deprecation warning).
CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP = True
# visibility_timeout must stay well above our longest countdown — the
# event-details debounce (PortalSettings.event_details_notify_debounce_seconds,
# default 900s) — so a delayed task is never redelivered before it fires.
CELERY_BROKER_TRANSPORT_OPTIONS = {'visibility_timeout': 3600}

# Under pytest or `manage.py test`, run tasks synchronously instead of via
# .delay(). Several services (reminders.services.create_reminder, the
# document_hub/meetings digest tasks) queue a notification as a side effect;
# without this, .delay() tries to reach the real Redis broker, and if nothing
# is listening there (true whenever Redis isn't running locally) the call
# hangs indefinitely rather than failing fast — discovered when a test run
# against apps/reminders/tests.py hung with zero output for 8+ minutes.
# conftest.py sets the same flag directly on the Celery app for pytest; this
# settings-level check additionally covers `manage.py test`, which never
# loads conftest.py.
TESTING = 'pytest' in sys.modules or (len(sys.argv) > 1 and sys.argv[1] == 'test')
if TESTING:
    CELERY_TASK_ALWAYS_EAGER = True
    CELERY_TASK_EAGER_PROPAGATES = True

# DB-backed schedule via django-celery-beat (DatabaseScheduler), so the timing
# of every periodic task is editable from the Django admin (Periodic Tasks) with
# no redeploy — and, critically, so it matches the home-server `celerybeat@`
# systemd unit, which hardcodes `--scheduler
# django_celery_beat.schedulers:DatabaseScheduler`. A static CELERY_BEAT_SCHEDULE
# would be silently ignored under that scheduler, stranding every periodic task.
# The default schedule (the four existing jobs + the Brevo health probe) is
# installed by the idempotent `manage.py seed_periodic_tasks` command; run it
# once per environment after `migrate`.
CELERY_BEAT_SCHEDULER = 'django_celery_beat.schedulers:DatabaseScheduler'

CORS_ALLOWED_ORIGINS = env.list('CORS_ALLOWED_ORIGINS')

# Origin of the client portal (e.g. "https://hephluxe.com"). The single source
# of truth for "where does the frontend live" — every URL the backend puts in an
# email is built from it via apps/core/deeplinks.py (absolute_url / login_url),
# because a relative route is meaningless in an inbox.
#
# Replaces the old FRONTEND_LOGIN_URL, which named the same deployment a second
# time (as a full ".../login" URL) purely for the credentials email. Two vars
# for one deployment is a drift hazard: point one at staging, forget the other,
# and the credentials email quietly sends people to the wrong environment.
#
# REQUIRED, and deliberately so: the credentials email is unusable without a
# login link, and a hardcoded default in the code is the same drift hazard by
# another name — it would let a misconfigured deploy silently mail users a link
# to someone else's environment instead of failing loudly here at boot.
FRONTEND_BASE_URL = env('FRONTEND_BASE_URL')
if not FRONTEND_BASE_URL.strip():
    raise ImproperlyConfigured(
        "FRONTEND_BASE_URL must be set to the client portal's origin "
        "(e.g. http://localhost:3000 in dev, https://hephluxe.com in production). "
        "Every email link — the login CTA, reminder deep links — is built from it."
    )
FRONTEND_BASE_URL = FRONTEND_BASE_URL.strip()

# NOTE: the "Contact Your Team" email/WhatsApp number used to live here as
# HEPHZIBAH_CONTACT (env-sourced). It's now admin-configurable — see
# portal.PortalSettings.contact_email / contact_whatsapp — so staff can
# update it without a redeploy.

# NOTE: the "event details updated" notification debounce window used to live
# here as EVENT_DETAILS_NOTIFY_DEBOUNCE_SECONDS. It's now admin-configurable —
# see portal.PortalSettings.event_details_notify_debounce_seconds — so staff
# can change it without a redeploy.


# ---------------------------------------------------------------------------
# Cache — its own Redis (django-redis), separate from Celery; LocMem fallback
# ---------------------------------------------------------------------------
# Distinct from REDIS_URL (Celery) on purpose — this is the data cache: it backs
# rate-limit counters and fast data caching, and should live on its own Redis DB
# index so cache operations never touch the Celery broker/queue (same split the
# storefront uses). On the home server the control panel allocates a dedicated
# cache index (e.g. redis://192.168.2.21:6379/5). Leave blank in dev to fall back
# to in-process LocMem. /health/ready/ checks whichever is active.
CACHE_REDIS_URL = env('CACHE_REDIS_URL', default='').strip()
# Force LocMem under the test runner regardless of CACHE_REDIS_URL, so a test's
# cache.clear() (used to reset rate-limit counters) can never FLUSHDB a real,
# possibly-shared Redis cache.
if CACHE_REDIS_URL and not TESTING:
    CACHES = {
        'default': {
            'BACKEND': 'django_redis.cache.RedisCache',
            'LOCATION': CACHE_REDIS_URL,
            'OPTIONS': {'CLIENT_CLASS': 'django_redis.client.DefaultClient'},
        }
    }
else:
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        }
    }


# ---------------------------------------------------------------------------
# Observability — structured logging + Sentry/GlitchTip
# ---------------------------------------------------------------------------
# The app EMITS signals (structured JSON logs -> Loki, error/trace events ->
# GlitchTip); the self-hosted monitoring stack (Grafana/GlitchTip -> ntfy)
# decides alerts. See docs/OBSERVABILITY_STANDARD.md. Every sink is env-gated:
# an unset DSN / Loki URL is a silent no-op, so dev/CI/test stay quiet.
from apps.core.logging import build_logging_config  # noqa: E402

LOG_LEVEL = env('LOG_LEVEL', default='INFO').upper()
# "json" (one object per line -> Loki/Grafana) in prod; "console" for local dev.
LOG_FORMAT = env('LOG_FORMAT', default='console').lower()

# Loki push (optional) — the home-server Loki endpoint is
# http://192.168.2.21:3100/loki/api/v1/push behind HTTP basic auth. Leave unset
# to disable (no Loki handler is added, logging_loki is never referenced).
LOKI_PUSH_URL = env('LOKI_PUSH_URL', default='')
LOKI_PUSH_USER = env('LOKI_PUSH_USER', default='')
LOKI_PUSH_PASSWORD = env('LOKI_PUSH_PASSWORD', default='')

# Reused as the Loki `environment` label and Sentry environment tag, so one
# monitoring stack separates deploys (homelab / production / development) by tag.
SENTRY_ENVIRONMENT = env('SENTRY_ENVIRONMENT', default='development')

LOGGING = build_logging_config(
    log_level=LOG_LEVEL,
    json_logs=(LOG_FORMAT == 'json'),
    loki_url=LOKI_PUSH_URL,
    loki_auth=(LOKI_PUSH_USER, LOKI_PUSH_PASSWORD) if (LOKI_PUSH_USER and LOKI_PUSH_PASSWORD) else None,
    loki_tags={'service': 'hephzibah-api', 'environment': SENTRY_ENVIRONMENT},
)

# Sentry / GlitchTip — DSN-guarded, so unset (dev/test/CI) means it never
# initialises. GlitchTip speaks the Sentry ingest protocol; point SENTRY_DSN at
# a GlitchTip project's DSN.
SENTRY_DSN = env('SENTRY_DSN', default='')
SENTRY_RELEASE = os.getenv('SENTRY_RELEASE') or os.getenv('GIT_SHA') or None
SENTRY_TRACES_SAMPLE_RATE = env.float('SENTRY_TRACES_SAMPLE_RATE', default=0.1)

if SENTRY_DSN and not TESTING:
    from apps.core.observability import init_sentry  # noqa: E402

    init_sentry(
        dsn=SENTRY_DSN,
        environment=SENTRY_ENVIRONMENT,
        release=SENTRY_RELEASE,
        traces_sample_rate=SENTRY_TRACES_SAMPLE_RATE,
    )


# ---------------------------------------------------------------------------
# Rate limiting (django-ratelimit)
# ---------------------------------------------------------------------------
# Counters live in the `default` cache (see CACHES above). For correct
# cross-worker counting in production, CACHE_REDIS_URL must point at Redis; with
# the LocMem fallback each gunicorn worker keeps its own counters, so the
# effective limit is multiplied by the worker count.
#
# The middleware catches the Ratelimited exception raised by @ratelimit(block=True)
# and renders this view — the standard {detail, code} 429. See apps/core/views.ratelimited.
RATELIMIT_VIEW = "apps.core.views.ratelimited"

# Disabled under test so the suite isn't throttled; rate-limit tests opt back in
# with @override_settings(RATELIMIT_ENABLE=True).
RATELIMIT_ENABLE = not TESTING

# Per-endpoint limits, "count/period" (period: s, m, h, d, or a multiple like
# "15m"). Env-tunable per deploy; the *key* each counts against (IP vs IP+email)
# is wired at the URL in apps/accounts/urls.py, not here. Defaults match
# .env.example so the app boots without them (and the active value stays visible
# there). Consumed via apps/core/ratelimit.RATE_LIMITS.
RATE_LIMITS = {
    "auth_login":              env("RATE_LIMIT_AUTH_LOGIN", default="5/m"),
    "token_refresh":           env("RATE_LIMIT_TOKEN_REFRESH", default="30/m"),
    "password_reset_request":  env("RATE_LIMIT_PASSWORD_RESET_REQUEST", default="3/h"),
    "password_reset_verify":   env("RATE_LIMIT_PASSWORD_RESET_VERIFY", default="10/m"),
    "password_reset_confirm":  env("RATE_LIMIT_PASSWORD_RESET_CONFIRM", default="10/m"),
}
