web: python manage.py collectstatic --noinput && gunicorn config.wsgi:application --bind 0.0.0.0:$PORT --workers 3 --timeout 60
worker: celery -A config worker --loglevel warning --without-gossip --without-mingle --without-heartbeat
beat: celery -A config beat --loglevel warning
