# Generated by Django 5.2.10 on 2026-07-15 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notificationsettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationTypeSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_name', models.CharField(choices=[('new_reminder', 'New reminder'), ('payment_due', 'Payment due'), ('meeting_prep_due', 'Meeting prep due'), ('phase_advanced', 'Planning phase advanced'), ('event_details_updated', 'Event details updated')], max_length=100, unique=True)),
                ('enabled', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Notification Type Setting',
                'verbose_name_plural': 'Notification Type Settings',
                'ordering': ['template_name'],
            },
        ),
        migrations.DeleteModel(
            name='NotificationSettings',
        ),
    ]
