# Generated by Django 5.2.10 on 2026-07-16 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_seed_document_hub_notification_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationtypesettings',
            name='template_name',
            field=models.CharField(choices=[('new_reminder', 'New reminder'), ('payment_due', 'Payment due'), ('meeting_prep_due', 'Meeting prep due'), ('phase_advanced', 'Planning phase advanced'), ('event_details_updated', 'Event details updated'), ('document_added', 'Document added'), ('invoice_issued', 'Invoice issued'), ('receipt_issued', 'Receipt issued'), ('milestone_paid', 'Payment milestone paid')], max_length=100, unique=True),
        ),
    ]
