# Generated by Django 5.2.10 on 2026-07-16 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0008_seed_accounts_notification_types'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledTaskSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_key', models.CharField(max_length=100, unique=True)),
                ('label', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('is_enabled', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Scheduled Task Setting',
                'verbose_name_plural': 'Scheduled Task Settings',
                'ordering': ['label'],
            },
        ),
    ]
