# Generated by Django 5.2.10 on 2026-07-16 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0010_seed_scheduled_task_settings'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceHealthState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(max_length=50, unique=True)),
                ('status', models.CharField(choices=[('up', 'Up'), ('down', 'Down'), ('unknown', 'Unknown')], default='unknown', max_length=10)),
                ('consecutive_failures', models.IntegerField(default=0)),
                ('last_ok_at', models.DateTimeField(blank=True, null=True)),
                ('last_failure_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Service Health State',
                'verbose_name_plural': 'Service Health States',
                'ordering': ['service'],
            },
        ),
    ]
