# Generated by Django 5.2.10 on 2026-10-05 14:01

import apps.core.storages
import apps.core.uploads
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_drop_celery_beat_tables'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeStripImage',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(max_length=500, storage=apps.core.storages.select_public_media_storage, upload_to='home-strip/', validators=[apps.core.uploads.validate_image_model_field])),
                ('alt_text', models.CharField(blank=True, max_length=255)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_published', models.BooleanField(default=False)),
                ('import_key', models.CharField(default=uuid.uuid4, editable=False, max_length=255, unique=True)),
            ],
            options={
                'ordering': ('sort_order', 'created_at', 'id'),
            },
        ),
    ]
