# Generated by Django 5.2.10 on 2026-05-18 18:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('country', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('event_date', models.DateField(help_text='Date when the event takes place')),
                ('event_venue', models.CharField(help_text='Venue where the event takes place', max_length=255, null=True)),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='event_cover_picture')),
                ('event_type', models.CharField(blank=True, choices=[('Birthday', 'Birthday Party'), ('Wedding', 'Wedding'), ('Corporate', 'Corporate Event'), ('Social Events', 'Social Events'), ('Others', 'Others')], max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('groom_name', models.CharField(blank=True, max_length=255, null=True)),
                ('bride_name', models.CharField(blank=True, max_length=255, null=True)),
                ('honoree_name', models.CharField(blank=True, max_length=255, null=True)),
                ('event_name', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('celebrant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EventDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_day_title', models.CharField(blank=True, help_text='kind of event wedding intoduction, traditional, white wedding...', max_length=255, null=True)),
                ('date', models.DateField()),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_images', models.ImageField(blank=True, null=True, upload_to='event_day_picture')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='events.event')),
            ],
            options={
                'verbose_name_plural': 'Event Days',
                'ordering': ['date', 'start_time'],
            },
        ),
    ]
