# Generated by Django 5.2.12 on 2026-05-19 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventday',
            name='dress_code',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='eventday',
            name='estimated_guest_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventday',
            name='venue',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='eventday',
            name='venue_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='eventday',
            name='venue_booking_status',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
