# Generated by Django 5.2.10 on 2026-05-25 23:58

import apps.core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_eventday_dress_code_eventday_estimated_guest_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='featured_image',
            field=models.ImageField(blank=True, null=True, upload_to=apps.core.utils.event_cover_upload_path),
        ),
        migrations.AlterField(
            model_name='eventday',
            name='event_images',
            field=models.ImageField(blank=True, null=True, upload_to=apps.core.utils.event_image_upload_path),
        ),
    ]
