# Hand-written (not autogenerated): Django's default AlterField generates
# `id::uuid`, which Postgres rejects — there is no direct bigint->uuid cast.
# Both events_eventday and the dependent contacts_eventcontact.event_day_id
# are confirmed empty, so the safe fix is to drop and recreate the columns
# outright (with CASCADE to drop the now-mismatched FK constraint) rather
# than attempt an in-place type cast, then rebuild the FK against the new
# uuid column.

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_event_featured_image_and_more'),
        ('contacts', '0007_alter_eventcontact_event_day'),
    ]

    operations = [
        migrations.RunSQL(
            sql=(
                'ALTER TABLE events_eventday DROP COLUMN id CASCADE;'
                'ALTER TABLE events_eventday ADD COLUMN id uuid '
                'NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY;'
                'ALTER TABLE contacts_eventcontact ALTER COLUMN event_day_id '
                'TYPE uuid USING (event_day_id::text::uuid);'
                'ALTER TABLE contacts_eventcontact ADD CONSTRAINT '
                'contacts_eventcontact_event_day_id_fkey FOREIGN KEY (event_day_id) '
                'REFERENCES events_eventday(id) ON DELETE CASCADE;'
            ),
            reverse_sql=(
                'ALTER TABLE contacts_eventcontact DROP CONSTRAINT '
                'contacts_eventcontact_event_day_id_fkey;'
                'ALTER TABLE contacts_eventcontact ALTER COLUMN event_day_id TYPE bigint '
                'USING NULL;'
                'ALTER TABLE events_eventday DROP COLUMN id CASCADE;'
                'ALTER TABLE events_eventday ADD COLUMN id bigserial PRIMARY KEY;'
                'ALTER TABLE contacts_eventcontact ADD CONSTRAINT '
                'contacts_eventcontact_event_day_id_fkey FOREIGN KEY (event_day_id) '
                'REFERENCES events_eventday(id) ON DELETE CASCADE;'
            ),
            state_operations=[
                migrations.AlterField(
                    model_name='eventday',
                    name='id',
                    field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
                ),
            ],
        ),
    ]
