# Generated by Django 5.2.10 on 2026-07-13 01:49

import apps.core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_alter_eventday_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='featured_image',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to=apps.core.utils.event_cover_upload_path),
        ),
        migrations.AlterField(
            model_name='eventday',
            name='event_images',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to=apps.core.utils.event_image_upload_path),
        ),
    ]
