# Generated by Django 5.2.10 on 2026-07-15 21:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_alter_event_featured_image_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='last_updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='eventday',
            name='last_updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_event_days', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='eventday',
            name='venue_booking_status',
            field=models.CharField(blank=True, choices=[('not_booked', 'Not Booked'), ('pending', 'Pending'), ('confirmed', 'Confirmed')], max_length=20),
        ),
    ]
