# Generated by Django 5.2.10 on 2026-09-01 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_event_images_public_storage'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='headline',
            field=models.CharField(blank=True, help_text="Editorial headline for the public page, e.g. 'A Golden 50th: An Intimate Two-Day Celebration of Family, Faith & Joy'. Distinct from `title`, which is generated from the celebrant names and drives the portal.", max_length=255),
        ),
        migrations.AddField(
            model_name='eventday',
            name='headline',
            field=models.CharField(blank=True, help_text="Editorial headline for this day, e.g. 'A Moment Before Fifty - A Pre-Birthday Portrait Experience'.", max_length=255),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(blank=True, help_text='Long-form narrative for the public page — the paragraphs under `headline`.', null=True),
        ),
        migrations.AlterField(
            model_name='eventday',
            name='content',
            field=models.TextField(blank=True, help_text='Long-form narrative for this day — the paragraphs under `headline`. Short one-line summaries predate this field having a defined meaning and are still valid; they just render as a very short story.', null=True),
        ),
        migrations.AlterField(
            model_name='eventday',
            name='event_day_title',
            field=models.CharField(blank=True, help_text="Short label / eyebrow above the headline. Either the kind of day ('Traditional Wedding', 'Pre-Birthday Photoshoot') or its position in the sequence ('Event No. 1'). Typed as it should appear — the numbering is editorial, not computed, because not every day is part of the numbered sequence.", max_length=255, null=True),
        ),
    ]
