# Split by hand from the autogenerated migration. Creating the table has to come
# before dropping the columns it replaces, so the values can be carried across —
# see 0012, which does the carrying.

import apps.core.storages
import apps.core.utils
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_event_headline_eventday_headline_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(max_length=500, storage=apps.core.storages.select_public_media_storage, upload_to=apps.core.utils.event_gallery_upload_path)),
                ('alt_text', models.CharField(blank=True, help_text='Describes the photograph for screen readers and for when it fails to load.', max_length=255)),
                ('is_primary', models.BooleanField(default=False, help_text='The cover for this gallery. At most one per event, and one per event day.')),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Ascending display order within the gallery; ties break on upload time.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='events.event')),
                ('event_day', models.ForeignKey(blank=True, help_text='Set for a day gallery image; leave empty for an event-level image.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='events.eventday')),
                ('last_updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Event Image',
                'verbose_name_plural': 'Event Images',
                'ordering': ['sort_order', 'created_at'],
                'indexes': [models.Index(fields=['event', 'event_day', 'sort_order'], name='events_even_event_i_888773_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('event_day__isnull', True), ('is_primary', True)), fields=('event',), name='unique_primary_image_per_event'), models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('event_day',), name='unique_primary_image_per_event_day')],
            },
        ),
    ]
