# Generated by Django 5.2.10 on 2026-09-03 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_migrate_single_images_to_gallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_published',
            field=models.BooleanField(default=False, help_text='Show this event on the public portfolio. Off by default — publishing also exposes every event day and gallery image beneath it.'),
        ),
    ]
