# Generated by Django 5.2.10 on 2026-09-03 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_event_is_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventimage',
            name='is_published',
            field=models.BooleanField(default=True, help_text="Show this photograph on the public portfolio. Has no effect until the event itself is published. Untick to keep a shot in the client's portal without putting it on the website."),
        ),
    ]
