# Generated by Django 5.2.10 on 2026-10-04 22:41

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0014_eventimage_is_published'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='public_slug',
            field=models.SlugField(blank=True, help_text='Public URL of this event: /portfolio/<public slug>. Leave blank to generate it from the headline on save. Lowercase letters, numbers and hyphens. Changing it breaks any link already shared.', max_length=100, null=True, unique=True, validators=[django.core.validators.RegexValidator('^[a-z0-9]+(?:-[a-z0-9]+)*$', "Use lowercase letters, numbers and single hyphens only (e.g. 'golden-50th').", code='invalid_slug')]),
        ),
        migrations.AddField(
            model_name='eventday',
            name='slug',
            field=models.SlugField(blank=True, help_text='Public URL segment for this day, unique within its event. Leave blank to generate it from the label (or headline) on save.', max_length=100, null=True, validators=[django.core.validators.RegexValidator('^[a-z0-9]+(?:-[a-z0-9]+)*$', "Use lowercase letters, numbers and single hyphens only (e.g. 'golden-50th').", code='invalid_slug')]),
        ),
        migrations.AddConstraint(
            model_name='eventday',
            constraint=models.UniqueConstraint(condition=models.Q(('slug__isnull', False)), fields=('owner', 'slug'), name='unique_event_day_slug_per_event'),
        ),
    ]
