# Generated by Django 5.2.10 on 2026-05-19 06:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventContact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('primary', 'Primary Contacts'), ('decision_maker', 'Decision Makers & Approvals'), ('family_vip', 'Family & VIP Representatives'), ('key_participant', 'Key Participants'), ('event_day', 'Event-Day Contacts')], max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('role', models.CharField(blank=True, max_length=255)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('preferred_method', models.CharField(blank=True, choices=[('whatsapp', 'WhatsApp'), ('email', 'Email'), ('phone', 'Phone')], max_length=20)),
                ('photo', models.ImageField(blank=True, upload_to='contact_photos/')),
                ('last_updated_by', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='events.event')),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
    ]
