# Generated by Django 5.2.12 on 2026-05-19 19:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
        ('events', '0002_eventday_dress_code_eventday_estimated_guest_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventcontact',
            name='event_day',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='day_contacts', to='events.eventday'),
        ),
    ]
