# Generated by Django 5.2.10 on 2026-05-19 19:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_eventcontact_event_day'),
        ('events', '0002_eventday_dress_code_eventday_estimated_guest_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventcontact',
            name='event_day',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='day_contacts', to='events.eventday'),
        ),
    ]
