# Generated by Django 5.2.10 on 2026-05-19 21:19

from django.db import migrations, models


def remove_duplicate_contacts(apps, schema_editor):
    """Delete exact-duplicate contacts (same event, category, email) keeping the oldest."""
    EventContact = apps.get_model("contacts", "EventContact")
    from django.db.models import Min, Count

    duplicates = (
        EventContact.objects.filter(email__gt="")
        .values("event_id", "category", "email")
        .annotate(cnt=Count("id"), oldest=Min("created_at"))
        .filter(cnt__gt=1)
    )
    for dup in duplicates:
        # Keep the oldest, delete the rest
        EventContact.objects.filter(
            event_id=dup["event_id"],
            category=dup["category"],
            email=dup["email"],
        ).exclude(created_at=dup["oldest"]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_alter_eventcontact_event_day'),
        ('events', '0002_eventday_dress_code_eventday_estimated_guest_count_and_more'),
    ]

    operations = [
        migrations.RunPython(remove_duplicate_contacts, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='eventcontact',
            constraint=models.UniqueConstraint(condition=models.Q(('email__gt', '')), fields=('event', 'category', 'email'), name='unique_contact_per_category'),
        ),
    ]
