# Generated by Django 5.2.12 on 2026-05-20 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0004_eventcontact_unique_contact_per_category'),
        ('events', '0002_eventday_dress_code_eventday_estimated_guest_count_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='eventcontact',
            name='unique_contact_per_category',
        ),
        migrations.AddConstraint(
            model_name='eventcontact',
            constraint=models.UniqueConstraint(condition=models.Q(('email__gt', '')), fields=('event', 'event_day', 'category', 'email'), name='unique_contact_per_category_per_day'),
        ),
    ]
