# Generated by Django 5.2.10 on 2026-05-25 23:58

import apps.core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0005_remove_eventcontact_unique_contact_per_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventcontact',
            name='photo',
            field=models.ImageField(blank=True, upload_to=apps.core.utils.contact_photo_upload_path),
        ),
    ]
