# Generated by Django 5.2.12 on 2026-06-02 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0006_alter_eventcontact_photo'),
        ('events', '0003_alter_event_featured_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventcontact',
            name='event_day',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='day_contacts', to='events.eventday'),
        ),
    ]
