# Generated by Django 5.2.10 on 2026-07-13 02:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0008_alter_eventcontact_photo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # RemoveField + AddField, not AlterField: the old column is a plain
        # CharField holding free-text names ("tobi ojulari", etc.) that can't
        # be cast directly into the new ForeignKey's integer column — Postgres
        # rejects the implicit cast outright. Dropping and re-adding avoids
        # the cast attempt entirely. Old values are intentionally not
        # preserved (see docs/FAILURE_POINTS_AUDIT.md F11 — they were already
        # unreliable free-text snapshots, not real account references).
        migrations.RemoveField(
            model_name='eventcontact',
            name='last_updated_by',
        ),
        migrations.AddField(
            model_name='eventcontact',
            name='last_updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_contacts', to=settings.AUTH_USER_MODEL),
        ),
    ]
