# Generated by Django 5.2.10 on 2026-09-03 11:52

import apps.core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0011_eventcontact_photo_public_storage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventcontact',
            name='photo',
            field=models.ImageField(blank=True, max_length=500, upload_to=apps.core.utils.contact_photo_upload_path),
        ),
    ]
