# Generated by Django 5.2.12 on 2026-05-28 21:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('portal', '0002_clientportal_active_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase', models.CharField(choices=[('connect', 'No. 01: Connect'), ('align', 'No. 02: Align'), ('curate', 'No. 03: Curate'), ('envision', 'No. 04: Envision'), ('orchestrate', 'No. 05: Orchestrate'), ('deliver', 'No. 06: Deliver')], max_length=20)),
                ('author_name', models.CharField(max_length=255)),
                ('contact_method', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('email', 'Email')], default='whatsapp', max_length=20)),
                ('title', models.TextField()),
                ('body', models.TextField()),
                ('tags', models.JSONField(blank=True, default=list)),
                ('links', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('portal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='portal.clientportal')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
