# Generated by Django 5.2.10 on 2026-06-02 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conversation',
            old_name='author_name',
            new_name='conversation_with',
        ),
    ]
