# Generated by Django 5.2.12 on 2026-06-02 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0002_rename_author_name_conversation_conversation_with'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='portal',
        ),
    ]
