# Generated by Django 5.2.12 on 2026-06-02 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0003_remove_conversation_portal'),
        ('portal', '0004_remove_clientportal_active_event_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='engagement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='portal.eventengagement'),
        ),
    ]
