# Generated by Django 5.2.10 on 2026-07-10 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0004_conversation_engagement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='contact_method',
            field=models.CharField(choices=[('whatsapp', 'WhatsApp'), ('phone', 'Phone'), ('email', 'Email')], default='whatsapp', max_length=20),
        ),
    ]
