# Hand-written (not autogenerated): Django's default AlterField generates
# `id::uuid`, which Postgres rejects — there is no direct bigint->uuid cast.
# Since this table is confirmed empty (verified before writing this
# migration), the safe fix is to drop and recreate the column outright rather
# than attempt an in-place type cast. No dependent FKs point at Conversation
# from other tables, so no downstream fixups are needed.

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0005_alter_conversation_contact_method'),
    ]

    operations = [
        migrations.RunSQL(
            sql=(
                'ALTER TABLE conversations_conversation DROP COLUMN id;'
                'ALTER TABLE conversations_conversation ADD COLUMN id uuid '
                'NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY;'
            ),
            reverse_sql=(
                'ALTER TABLE conversations_conversation DROP COLUMN id;'
                'ALTER TABLE conversations_conversation ADD COLUMN id bigserial PRIMARY KEY;'
            ),
            state_operations=[
                migrations.AlterField(
                    model_name='conversation',
                    name='id',
                    field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
                ),
            ],
        ),
    ]
