# Generated by Django 5.2.10 on 2026-05-18 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InquiryForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('phone_number', models.CharField(max_length=20)),
                ('contact_mode', models.CharField(blank=True, choices=[('Email', 'Email'), ('Phone Number', 'Phone Number')], max_length=12, null=True)),
                ('event_type', models.CharField(blank=True, choices=[('Birthday', 'Birthday Party'), ('Wedding', 'Wedding'), ('Corporate', 'Corporate Event'), ('Social Events', 'Social Events'), ('Others', 'Others')], max_length=20, null=True)),
                ('preferred_start_date', models.DateField(null=True)),
                ('preferred_end_date', models.DateField(null=True)),
                ('desired_location', models.CharField(max_length=255)),
                ('budget', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('details', models.TextField(blank=True, null=True)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('preferred_end_date__gte', models.F('preferred_start_date'))), name='valid_preferred_date_range')],
            },
        ),
    ]
