# Hand-written (not autogenerated): Django's default AlterField generates
# `id::uuid`, which Postgres rejects — there is no direct bigint->uuid cast.
# This table is confirmed EMPTY (0 rows, verified against the live database
# before writing this migration) and NO foreign key anywhere in the schema
# points at InquiryForm, so the safe fix is to drop and recreate the column
# outright rather than attempt an in-place type cast — there are no downstream
# fixups to make.
#
# Notes for whoever reads this against production:
#   * DROP COLUMN id drops the primary-key constraint with it; the ADD COLUMN
#     below re-establishes it, so no separate constraint statements are needed.
#   * The valid_preferred_date_range CHECK constraint does not reference `id`,
#     so it is untouched by this and survives the swap.
#   * gen_random_uuid() is VOLATILE, so on a populated table this rewrites every
#     row with a distinct value (which is what you want for a fresh PK) — moot
#     here at 0 rows, but true and worth knowing. gen_random_uuid() is built in
#     from PostgreSQL 13; this server is 17.10, so no pgcrypto extension needed.

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiries', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
            sql=(
                'ALTER TABLE inquiries_inquiryform DROP COLUMN id;'
                'ALTER TABLE inquiries_inquiryform ADD COLUMN id uuid '
                'NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY;'
            ),
            reverse_sql=(
                'ALTER TABLE inquiries_inquiryform DROP COLUMN id;'
                'ALTER TABLE inquiries_inquiryform ADD COLUMN id bigserial PRIMARY KEY;'
            ),
            state_operations=[
                migrations.AlterField(
                    model_name='inquiryform',
                    name='id',
                    field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
                ),
            ],
        ),
    ]
