# Generated by Django 5.2.10 on 2026-08-18 17:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiries', '0002_alter_inquiryform_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inquiryform',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='inquiryform',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inquiryform',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('qualified', 'Qualified'), ('converted', 'Converted'), ('lost', 'Lost'), ('archived', 'Archived')], default='new', max_length=20),
        ),
        migrations.AddField(
            model_name='inquiryform',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='inquiryform',
            name='budget',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
    ]
