# Generated by Django 5.2.10 on 2026-05-18 17:34

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('first_name', models.CharField(max_length=255, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=255, verbose_name='Last Name')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='Email')),
                ('password', models.CharField(max_length=255)),
                ('force_password_change', models.BooleanField(default=False, help_text='If True, user must change password before accessing the system')),
                ('temporary_password_created_at', models.DateTimeField(blank=True, help_text='Timestamp when temporary password was created', null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('country', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('event_date', models.DateField(help_text='Date when the event takes place')),
                ('event_venue', models.CharField(help_text='Venue where the event takes place', max_length=255, null=True)),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='event_cover_picture')),
                ('event_type', models.CharField(blank=True, choices=[('Birthday', 'Birthday Party'), ('Wedding', 'Wedding'), ('Corporate', 'Corporate Event'), ('Social Events', 'Social Events'), ('Others', 'Others')], max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('groom_name', models.CharField(blank=True, max_length=255, null=True)),
                ('bride_name', models.CharField(blank=True, max_length=255, null=True)),
                ('honoree_name', models.CharField(blank=True, max_length=255, null=True)),
                ('event_name', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('celebrant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EventDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_day_title', models.CharField(blank=True, help_text='kind of event wedding intoduction, traditional, white wedding...', max_length=255, null=True)),
                ('date', models.DateField()),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_images', models.ImageField(blank=True, null=True, upload_to='event_day_picture')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='accounts.event')),
            ],
            options={
                'verbose_name_plural': 'Event Days',
                'ordering': ['date', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='InquiryForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('phone_number', models.CharField(max_length=20)),
                ('contact_mode', models.CharField(blank=True, choices=[('Email', 'Email'), ('Phone Number', 'Phone Number')], max_length=12, null=True)),
                ('event_type', models.CharField(blank=True, choices=[('Birthday', 'Birthday Party'), ('Wedding', 'Wedding'), ('Corporate', 'Corporate Event'), ('Social Events', 'Social Events'), ('Others', 'Others')], max_length=20, null=True)),
                ('preferred_start_date', models.DateField(null=True)),
                ('preferred_end_date', models.DateField(null=True)),
                ('desired_location', models.CharField(max_length=255)),
                ('budget', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('details', models.TextField(blank=True, null=True)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('preferred_end_date__gte', models.F('preferred_start_date'))), name='valid_preferred_date_range')],
            },
        ),
        migrations.CreateModel(
            name='PasswordResetToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('is_used', models.BooleanField(default=False)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('ip_address', models.CharField(blank=True, max_length=45)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_reset_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_used', 'expires_at'], name='accounts_pa_user_id_eae84d_idx'), models.Index(fields=['code', 'is_used'], name='accounts_pa_code_fb22d0_idx')],
            },
        ),
    ]
