# Generated by Django 5.2.10 on 2026-05-18 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_eventday_owner_delete_event_delete_eventday'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InquiryForm',
        ),
    ]
