# Generated by Django 5.2.10 on 2026-05-19 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_delete_inquiryform'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('client', 'Client'), ('staff', 'Staff'), ('admin', 'Admin')], default='client', max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='force_password_change',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='temporary_password_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
