# Generated by Django 5.2.10 on 2026-08-18 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_deactivated_at_user_deactivated_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='receives_inquiry_alerts',
            field=models.BooleanField(default=False, help_text='Receive an email for every inquiry submitted through the public form.'),
        ),
    ]
