# Generated by Django 5.2.10 on 2026-08-28 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_hash_password_reset_codes'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='timezone',
            field=models.CharField(blank=True, help_text="IANA timezone name, e.g. Africa/Lagos. Blank uses the platform default. Sets which calendar day this account's payment-due and meeting-prep digests are computed against.", max_length=64),
        ),
    ]
