# Generated by Django 5.2.10 on 2026-08-29 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_user_timezone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='failed_login_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='failed_login_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
