# Generated by Django 5.2.10 on 2026-05-19 06:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=255)),
                ('bio', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, upload_to='team_photos/')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ClientPortal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('welcome_message', models.TextField(blank=True)),
                ('current_phase', models.CharField(choices=[('connect', 'No. 01: Connect'), ('align', 'No. 02: Align'), ('curate', 'No. 03: Curate'), ('envision', 'No. 04: Envision'), ('orchestrate', 'No. 05: Orchestrate'), ('deliver', 'No. 06: Deliver')], default='connect', max_length=20)),
                ('phase_details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='portal', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PortalTeamAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_assignments', to='portal.clientportal')),
                ('team_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.teammember')),
            ],
            options={
                'unique_together': {('portal', 'team_member')},
            },
        ),
    ]
