# Generated by Django 5.2.12 on 2026-05-19 20:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_eventday_dress_code_eventday_estimated_guest_count_and_more'),
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientportal',
            name='active_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='portal_active', to='events.event'),
        ),
    ]
