# Generated by Django 5.2.12 on 2026-06-02 17:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_event_featured_image_and_more'),
        ('portal', '0003_clientportal_contacts_locked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientportal',
            name='active_event',
        ),
        migrations.RemoveField(
            model_name='clientportal',
            name='contacts_locked',
        ),
        migrations.RemoveField(
            model_name='clientportal',
            name='current_phase',
        ),
        migrations.RemoveField(
            model_name='clientportal',
            name='phase_details',
        ),
        migrations.CreateModel(
            name='EventEngagement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('current_phase', models.CharField(choices=[('connect', 'No. 01: Connect'), ('align', 'No. 02: Align'), ('curate', 'No. 03: Curate'), ('envision', 'No. 04: Envision'), ('orchestrate', 'No. 05: Orchestrate'), ('deliver', 'No. 06: Deliver')], default='connect', max_length=20)),
                ('phase_details', models.JSONField(blank=True, default=dict)),
                ('contacts_locked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='engagement', to='events.event')),
                ('portal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engagements', to='portal.clientportal')),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('portal',), name='unique_active_engagement_per_portal')],
            },
        ),
    ]
