# Generated by Django 5.2.12 on 2026-06-02 19:14

import apps.portal.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_remove_clientportal_active_event_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='photo',
            field=models.ImageField(blank=True, upload_to=apps.portal.models.team_photo_upload_path),
        ),
    ]
