# Generated by Django 5.2.10 on 2026-07-12 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_alter_teammember_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventengagement',
            name='event_details_locked',
            field=models.BooleanField(default=False),
        ),
    ]
