# Generated by Django 5.2.10 on 2026-07-15 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0006_eventengagement_event_details_locked'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventengagement',
            name='reference_segment',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
