# Generated by Django 5.2.10 on 2026-07-15 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0007_eventengagement_reference_segment'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='is_default',
            field=models.BooleanField(default=False, help_text='Auto-assigned to every new client portal.'),
        ),
    ]
