# Generated by Django 5.2.10 on 2026-07-15 21:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0008_teammember_is_default'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PortalSettings',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('auto_lock_enabled', models.BooleanField(default=False, help_text='Master switch for phase-based auto-locking.')),
                ('auto_lock_phase', models.CharField(choices=[('connect', 'No. 01: Connect'), ('align', 'No. 02: Align'), ('curate', 'No. 03: Curate'), ('envision', 'No. 04: Envision'), ('orchestrate', 'No. 05: Orchestrate'), ('deliver', 'No. 06: Deliver')], default='orchestrate', help_text='Locking kicks in when the engagement reaches this phase (or later).', max_length=20)),
                ('auto_lock_event_details', models.BooleanField(default=True, help_text='Auto-lock event/event-day editing.')),
                ('auto_lock_contacts', models.BooleanField(default=True, help_text='Auto-lock contact editing.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Portal Settings',
                'verbose_name_plural': 'Portal Settings',
            },
        ),
        migrations.AddField(
            model_name='eventengagement',
            name='phase_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventengagement',
            name='phase_updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='phase_updates', to=settings.AUTH_USER_MODEL),
        ),
    ]
