# Generated by Django 5.2.10 on 2026-07-15 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0009_portalsettings_eventengagement_phase_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventengagement',
            name='event_details_notify_token',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
