# Generated by Django 5.2.10 on 2026-07-15 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0010_eventengagement_event_details_notify_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='portalsettings',
            name='event_details_notify_debounce_seconds',
            field=models.PositiveIntegerField(default=900, help_text="Seconds of inactivity on an event (or its event days) before the 'event details updated' client email sends. Every edit resets this window, so a burst of edits collapses into one email. Default 900 = 15 min."),
        ),
    ]
