# Generated by Django 5.2.10 on 2026-07-16 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0011_portalsettings_event_details_notify_debounce_seconds'),
    ]

    operations = [
        migrations.AddField(
            model_name='portalsettings',
            name='contact_email',
            field=models.EmailField(blank=True, help_text="Shown on the client portal's 'Contact Your Team' — Send an Email.", max_length=254),
        ),
        migrations.AddField(
            model_name='portalsettings',
            name='contact_whatsapp',
            field=models.CharField(blank=True, help_text="WhatsApp number for 'Contact Your Team' — Send a Message. Include the country code (e.g. +2348023203870); this is rendered into a wa.me link.", max_length=32),
        ),
    ]
