# Generated by Django 5.2.10 on 2026-08-26 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0014_clientportal_created_by_clientportal_last_updated_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventengagement',
            name='event_details_notify_due_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='eventengagement',
            name='event_details_notify_what',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
