# Generated by Django 5.2.10 on 2026-09-03 11:52

import apps.core.storages
import apps.portal.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0015_event_details_notify_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='photo',
            field=models.ImageField(blank=True, max_length=500, storage=apps.core.storages.select_public_media_storage, upload_to=apps.portal.models.team_photo_upload_path),
        ),
    ]
