# Generated by Django 5.2.12 on 2026-06-02 17:46

import apps.core.utils
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0003_alter_event_featured_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventBudget',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_budget', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='budget', to='events.event')),
            ],
        ),
        migrations.CreateModel(
            name='BudgetPayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('payment_date', models.DateField()),
                ('vendor_item', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('venue', 'Venue & Location'), ('catering', 'Catering'), ('photography', 'Photography & Videography'), ('decor', 'Decor & Design'), ('music', 'Music & Entertainment'), ('attire', 'Attire & Accessories'), ('stationery', 'Stationery'), ('souvenir', 'Souvenir'), ('other', 'Other')], max_length=20)),
                ('purpose', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('status', models.CharField(choices=[('paid', 'Paid'), ('pending', 'Pending')], default='pending', max_length=10)),
                ('receipt', models.FileField(blank=True, null=True, upload_to=apps.core.utils.budget_receipt_upload_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='budgets.eventbudget')),
            ],
            options={
                'ordering': ['-payment_date'],
            },
        ),
        migrations.CreateModel(
            name='BudgetCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('venue', 'Venue & Location'), ('catering', 'Catering'), ('photography', 'Photography & Videography'), ('decor', 'Decor & Design'), ('music', 'Music & Entertainment'), ('attire', 'Attire & Accessories'), ('stationery', 'Stationery'), ('souvenir', 'Souvenir'), ('other', 'Other')], max_length=20)),
                ('estimated_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('actual_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('notes', models.TextField(blank=True)),
                ('order', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='budgets.eventbudget')),
            ],
            options={
                'ordering': ['order', 'category'],
                'unique_together': {('budget', 'category')},
            },
        ),
    ]
