# Generated by Django 5.2.10 on 2026-07-13 01:49

import apps.core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgetpayment',
            name='receipt',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to=apps.core.utils.budget_receipt_upload_path),
        ),
    ]
