# Generated by Django 5.2.12 on 2026-06-02 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='portal',
        ),
    ]
