# Generated by Django 5.2.10 on 2026-07-13 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_remove_document_file_document_file_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='object_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
