# Generated by Django 5.2.10 on 2026-07-10 10:51

import apps.core.utils
import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('portal', '0005_alter_teammember_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('invoice_number', models.CharField(max_length=50, unique=True, validators=[django.core.validators.RegexValidator(message="Reference code must look like 'HL-PSW001-C001'.", regex='^HL-[A-Za-z0-9]+-[A-Za-z]+\\d+$')])),
                ('issued_on', models.DateField()),
                ('due_on', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('status', models.CharField(choices=[('paid', 'Paid'), ('pending', 'Pending')], default='pending', max_length=10)),
                ('file', models.FileField(blank=True, null=True, upload_to=apps.core.utils.invoice_upload_path)),
                ('engagement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='portal.eventengagement')),
            ],
            options={
                'ordering': ['-issued_on'],
            },
        ),
        migrations.CreateModel(
            name='PaymentSchedule',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_investment', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('engagement', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment_schedule', to='portal.eventengagement')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PaymentMilestone',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('paid_on', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('paid', 'Paid'), ('pending', 'Pending')], default='pending', max_length=10)),
                ('order', models.IntegerField(default=0)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='document_hub.paymentschedule')),
            ],
            options={
                'ordering': ['order', 'due_date'],
            },
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('receipt_number', models.CharField(max_length=50, unique=True, validators=[django.core.validators.RegexValidator(message="Reference code must look like 'HL-PSW001-C001'.", regex='^HL-[A-Za-z0-9]+-[A-Za-z]+\\d+$')])),
                ('paid_on', models.DateField()),
                ('payment_for', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('file', models.FileField(blank=True, null=True, upload_to=apps.core.utils.receipt_upload_path)),
                ('engagement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='portal.eventengagement')),
            ],
            options={
                'ordering': ['-paid_on'],
            },
        ),
        migrations.CreateModel(
            name='ClientDocument',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('contract', 'Service Agreement'), ('quotation', 'Quotation'), ('welcome_booklet', 'Welcome Booklet'), ('faq', 'Frequently Asked Questions'), ('other', 'Other')], max_length=20)),
                ('reference_code', models.CharField(blank=True, help_text="Only used for Service Agreement / Quotation, e.g. 'HL-PSW001-C001'.", max_length=50, validators=[django.core.validators.RegexValidator(message="Reference code must look like 'HL-PSW001-C001'.", regex='^HL-[A-Za-z0-9]+-[A-Za-z]+\\d+$')])),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('file', models.FileField(upload_to=apps.core.utils.client_document_upload_path)),
                ('is_signed', models.BooleanField(default=False)),
                ('signed_on', models.DateField(blank=True, null=True)),
                ('order', models.IntegerField(default=0)),
                ('engagement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_documents', to='portal.eventengagement')),
            ],
            options={
                'ordering': ['order', '-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('reference_code__gt', '')), fields=('reference_code',), name='unique_client_document_reference_code')],
            },
        ),
    ]
