# Generated by Django 5.2.10 on 2026-07-10 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_hub', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmilestone',
            name='reminder_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
