# Generated by Django 5.2.10 on 2026-07-13 01:49

import apps.core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_hub', '0002_paymentmilestone_reminder_sent_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientdocument',
            name='file',
            field=models.FileField(max_length=500, upload_to=apps.core.utils.client_document_upload_path),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='file',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to=apps.core.utils.invoice_upload_path),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='file',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to=apps.core.utils.receipt_upload_path),
        ),
    ]
