# Generated by Django 5.2.10 on 2026-07-15 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_hub', '0003_alter_clientdocument_file_alter_invoice_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmilestone',
            name='percentage',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Share of total_investment; a schedule's percentage-based milestones must sum to 100.", max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='paymentmilestone',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
