# Generated by Django 5.2.10 on 2026-07-15 13:16

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_hub', '0004_paymentmilestone_percentage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortalDefaults',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('service_agreement_file', models.FileField(blank=True, max_length=500, null=True, upload_to='portal_defaults/service_agreement/')),
                ('welcome_booklet_file', models.FileField(blank=True, max_length=500, null=True, upload_to='portal_defaults/welcome_booklet/')),
                ('faq_file', models.FileField(blank=True, max_length=500, null=True, upload_to='portal_defaults/faq/')),
                ('welcome_message', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Portal Defaults',
                'verbose_name_plural': 'Portal Defaults',
            },
        ),
    ]
