# Generated by Django 5.2.10 on 2026-07-15 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_hub', '0005_portaldefaults'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferenceCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(max_length=255, unique=True)),
                ('value', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
