# Generated by Django 5.2.10 on 2026-07-23 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_hub', '0009_clientdocument_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientdocument',
            name='category',
            field=models.CharField(choices=[('svc_agreement', 'Service Agreement'), ('quotation', 'Quotation'), ('welcome_booklet', 'Welcome Booklet'), ('faq', 'Frequently Asked Questions'), ('other', 'Other')], max_length=20),
        ),
    ]
