# Generated by Django 5.2.10 on 2026-05-25 23:58

import apps.core.utils
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('portal', '0002_clientportal_active_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('duration_minutes', models.IntegerField(default=60)),
                ('meeting_url', models.URLField(blank=True)),
                ('status', models.CharField(choices=[('upcoming', 'Upcoming'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('rescheduled', 'Rescheduled')], default='upcoming', max_length=20)),
                ('phase', models.CharField(choices=[('connect', 'No. 01: Connect'), ('align', 'No. 02: Align'), ('curate', 'No. 03: Curate'), ('envision', 'No. 04: Envision'), ('orchestrate', 'No. 05: Orchestrate'), ('deliver', 'No. 06: Deliver')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('preparation_required', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('portal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to='portal.clientportal')),
            ],
            options={
                'ordering': ['date', 'time'],
            },
        ),
        migrations.CreateModel(
            name='MeetingNotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.TextField()),
                ('key_discussions', models.JSONField(default=list)),
                ('key_decisions', models.JSONField(default=list)),
                ('action_items', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meeting', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='meetings.meeting')),
            ],
        ),
        migrations.CreateModel(
            name='MeetingPrepItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prep_items', to='meetings.meeting')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='PrepItemField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_type', models.CharField(choices=[('checkbox', 'Checkbox'), ('file_upload', 'File Upload'), ('qa', 'Question & Answer'), ('text', 'Text Input')], max_length=20)),
                ('label', models.CharField(max_length=255)),
                ('helper_text', models.TextField(blank=True)),
                ('is_required', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
                ('prep_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='meetings.meetingprepitem')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='PrepItemResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_value', models.TextField(blank=True)),
                ('file_value', models.FileField(blank=True, null=True, upload_to=apps.core.utils.prep_upload_path)),
                ('submitted_at', models.DateTimeField(auto_now=True)),
                ('field', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='response', to='meetings.prepitemfield')),
            ],
        ),
    ]
