# Generated by Django 5.2.12 on 2026-05-26 22:38

import apps.core.utils
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0002_alter_meeting_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meetingnotes',
            options={'verbose_name': 'Meeting Notes', 'verbose_name_plural': 'Meeting Notes'},
        ),
        migrations.RemoveField(
            model_name='prepitemresponse',
            name='file_value',
        ),
        migrations.CreateModel(
            name='PrepItemFileUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=apps.core.utils.prep_upload_path)),
                ('filename', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploads', to='meetings.prepitemfield')),
            ],
        ),
    ]
