# Generated by Django 5.2.12 on 2026-06-02 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0003_alter_meetingnotes_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='portal',
        ),
    ]
