# Generated by Django 5.2.10 on 2026-07-10 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0005_meeting_engagement'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='prep_reminder_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
