# Hand-written (not autogenerated): Django's default AlterField generates
# `id::uuid`, which Postgres rejects — there is no direct bigint->uuid cast.
# All affected tables are confirmed empty. Three PKs change in this app
# (Meeting, MeetingPrepItem, PrepItemField), each with its own dependents, so
# this runs as an explicit topological sequence: drop+recreate a PK column
# (CASCADE drops the now-mismatched dependent FK constraints automatically),
# then fix each dependent FK column's type and re-add its FK constraint,
# before moving on to the next PK in the chain.
#
#   Meeting.id         -> MeetingPrepItem.meeting_id, MeetingNotes.meeting_id (O2O)
#   MeetingPrepItem.id -> PrepItemField.prep_item_id
#   PrepItemField.id   -> PrepItemResponse.field_id (O2O), PrepItemFileUpload.field_id
#
# UNIQUE constraints backing the OneToOneFields (MeetingNotes.meeting,
# PrepItemResponse.field) are NOT dependent on the referenced table's PK
# column, so CASCADE does not touch them — only the FK constraints need
# re-adding here.

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0006_meeting_prep_reminder_sent_at'),
    ]

    operations = [
        # ── Meeting.id ──────────────────────────────────────────────
        migrations.RunSQL(
            sql=(
                'ALTER TABLE meetings_meeting DROP COLUMN id CASCADE;'
                'ALTER TABLE meetings_meeting ADD COLUMN id uuid '
                'NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY;'

                'ALTER TABLE meetings_meetingprepitem ALTER COLUMN meeting_id '
                'TYPE uuid USING (meeting_id::text::uuid);'
                'ALTER TABLE meetings_meetingprepitem ADD CONSTRAINT '
                'meetings_meetingprepitem_meeting_id_fkey FOREIGN KEY (meeting_id) '
                'REFERENCES meetings_meeting(id) ON DELETE CASCADE;'

                'ALTER TABLE meetings_meetingnotes ALTER COLUMN meeting_id '
                'TYPE uuid USING (meeting_id::text::uuid);'
                'ALTER TABLE meetings_meetingnotes ADD CONSTRAINT '
                'meetings_meetingnotes_meeting_id_fkey FOREIGN KEY (meeting_id) '
                'REFERENCES meetings_meeting(id) ON DELETE CASCADE;'
            ),
            reverse_sql=(
                'ALTER TABLE meetings_meetingnotes DROP CONSTRAINT meetings_meetingnotes_meeting_id_fkey;'
                'ALTER TABLE meetings_meetingnotes ALTER COLUMN meeting_id TYPE bigint USING NULL;'
                'ALTER TABLE meetings_meetingprepitem DROP CONSTRAINT meetings_meetingprepitem_meeting_id_fkey;'
                'ALTER TABLE meetings_meetingprepitem ALTER COLUMN meeting_id TYPE bigint USING NULL;'
                'ALTER TABLE meetings_meeting DROP COLUMN id CASCADE;'
                'ALTER TABLE meetings_meeting ADD COLUMN id bigserial PRIMARY KEY;'
                'ALTER TABLE meetings_meetingprepitem ADD CONSTRAINT '
                'meetings_meetingprepitem_meeting_id_fkey FOREIGN KEY (meeting_id) '
                'REFERENCES meetings_meeting(id) ON DELETE CASCADE;'
                'ALTER TABLE meetings_meetingnotes ADD CONSTRAINT '
                'meetings_meetingnotes_meeting_id_fkey FOREIGN KEY (meeting_id) '
                'REFERENCES meetings_meeting(id) ON DELETE CASCADE;'
            ),
            state_operations=[
                migrations.AlterField(
                    model_name='meeting',
                    name='id',
                    field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
                ),
            ],
        ),
        # ── MeetingPrepItem.id ──────────────────────────────────────
        migrations.RunSQL(
            sql=(
                'ALTER TABLE meetings_meetingprepitem DROP COLUMN id CASCADE;'
                'ALTER TABLE meetings_meetingprepitem ADD COLUMN id uuid '
                'NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY;'

                'ALTER TABLE meetings_prepitemfield ALTER COLUMN prep_item_id '
                'TYPE uuid USING (prep_item_id::text::uuid);'
                'ALTER TABLE meetings_prepitemfield ADD CONSTRAINT '
                'meetings_prepitemfield_prep_item_id_fkey FOREIGN KEY (prep_item_id) '
                'REFERENCES meetings_meetingprepitem(id) ON DELETE CASCADE;'
            ),
            reverse_sql=(
                'ALTER TABLE meetings_prepitemfield DROP CONSTRAINT meetings_prepitemfield_prep_item_id_fkey;'
                'ALTER TABLE meetings_prepitemfield ALTER COLUMN prep_item_id TYPE bigint USING NULL;'
                'ALTER TABLE meetings_meetingprepitem DROP COLUMN id CASCADE;'
                'ALTER TABLE meetings_meetingprepitem ADD COLUMN id bigserial PRIMARY KEY;'
                'ALTER TABLE meetings_prepitemfield ADD CONSTRAINT '
                'meetings_prepitemfield_prep_item_id_fkey FOREIGN KEY (prep_item_id) '
                'REFERENCES meetings_meetingprepitem(id) ON DELETE CASCADE;'
            ),
            state_operations=[
                migrations.AlterField(
                    model_name='meetingprepitem',
                    name='id',
                    field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
                ),
            ],
        ),
        # ── PrepItemField.id ────────────────────────────────────────
        migrations.RunSQL(
            sql=(
                'ALTER TABLE meetings_prepitemfield DROP COLUMN id CASCADE;'
                'ALTER TABLE meetings_prepitemfield ADD COLUMN id uuid '
                'NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY;'

                'ALTER TABLE meetings_prepitemresponse ALTER COLUMN field_id '
                'TYPE uuid USING (field_id::text::uuid);'
                'ALTER TABLE meetings_prepitemresponse ADD CONSTRAINT '
                'meetings_prepitemresponse_field_id_fkey FOREIGN KEY (field_id) '
                'REFERENCES meetings_prepitemfield(id) ON DELETE CASCADE;'

                'ALTER TABLE meetings_prepitemfileupload ALTER COLUMN field_id '
                'TYPE uuid USING (field_id::text::uuid);'
                'ALTER TABLE meetings_prepitemfileupload ADD CONSTRAINT '
                'meetings_prepitemfileupload_field_id_fkey FOREIGN KEY (field_id) '
                'REFERENCES meetings_prepitemfield(id) ON DELETE CASCADE;'
            ),
            reverse_sql=(
                'ALTER TABLE meetings_prepitemfileupload DROP CONSTRAINT meetings_prepitemfileupload_field_id_fkey;'
                'ALTER TABLE meetings_prepitemfileupload ALTER COLUMN field_id TYPE bigint USING NULL;'
                'ALTER TABLE meetings_prepitemresponse DROP CONSTRAINT meetings_prepitemresponse_field_id_fkey;'
                'ALTER TABLE meetings_prepitemresponse ALTER COLUMN field_id TYPE bigint USING NULL;'
                'ALTER TABLE meetings_prepitemfield DROP COLUMN id CASCADE;'
                'ALTER TABLE meetings_prepitemfield ADD COLUMN id bigserial PRIMARY KEY;'
                'ALTER TABLE meetings_prepitemresponse ADD CONSTRAINT '
                'meetings_prepitemresponse_field_id_fkey FOREIGN KEY (field_id) '
                'REFERENCES meetings_prepitemfield(id) ON DELETE CASCADE;'
                'ALTER TABLE meetings_prepitemfileupload ADD CONSTRAINT '
                'meetings_prepitemfileupload_field_id_fkey FOREIGN KEY (field_id) '
                'REFERENCES meetings_prepitemfield(id) ON DELETE CASCADE;'
            ),
            state_operations=[
                migrations.AlterField(
                    model_name='prepitemfield',
                    name='id',
                    field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
                ),
            ],
        ),
    ]
