# Generated by Django 5.2.10 on 2026-07-13 11:50

import apps.core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0007_alter_meeting_id_alter_meetingprepitem_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prepitemfileupload',
            name='file',
            field=models.FileField(max_length=255, upload_to=apps.core.utils.prep_upload_path),
        ),
    ]
